// Generated by CoffeeScript 1.7.1
var print, spawn;

print = require('util').print;

spawn = require('child_process').spawn;

task('build', 'Build js/ from src/', function() {
  var coffee;
  coffee = spawn('coffee', ['-c', '-o', 'js', 'src']);
  coffee.stderr.on('data', function(data) {
    var message;
    message = data.toString();
    if (message.search('is now called') < 0) {
      return process.stderr.write(message);
    }
  });
  coffee.stdout.on('data', function(data) {
    return print(data.toString());
  });
  return coffee.on('exit', function(code) {
    if (code === 0) {
      return typeof callback === "function" ? callback() : void 0;
    }
  });
});

task('watch', 'Watch src/ for changes', function() {
  var coffee;
  coffee = spawn('coffee', ['-w', '-c', '-o', 'js', 'src']);
  coffee.stderr.on('data', function(data) {
    return process.stderr.write(data.toString());
  });
  return coffee.stdout.on('data', function(data) {
    return print(data.toString());
  });
});
